### ISSUE TITLE
nodejs tweaking out(nodejs error)

### ISSUE THREAD

**Issue by yeetssite** [PvtTyphoon/lfm-rich-presence#12]
I'm not very experienced with javascript, but when I used npm to install the required packages/modules(whatever node calls them) I got these warnings:

```shell
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```
At first, I thought "whatever, hopefully it'll still work", but when running the script, node popped out this error:

```shell
~ $ node main.js
/data/data/com.termux/files/home/main.js:315
undefined
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/node_modules/pretty-ms/index.js from /data/data/com.termux/files/home/main.js not supported.
Instead change the require of index.js in /data/data/com.termux/files/home/main.js to a dynamic import() which is available in all CommonJS modules.
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at Object.<anonymous> (/data/data/com.termux/files/home/main.js:6:28)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v22.5.1
```
It seems to be a problem with outdated code meant for an older release of node. Normally, if this was python or almost literally anything else, I would just fix it myself(and this issue would probably be a pr instead), but unfortunately I have no idea how javascript works so I'm just gonna have to bug you to fix it instead. I doubt anything will happen seeing as this repo hasn't had a commit since last year.

**Comment by noobprograms** [comment]
Hey! The error message says that you need to replace the require command with the import command 
in your JS files, wherever you find the line 
`const var = require("abc")` where the var and abc can be any variable and package respectively, replace it with 
`import "something" from "abc"`
try this and lemme know if that solves your issue

**Comment by PvtTyphoon** [comment]
You can't use the rpc on android using termux, the mobile app no longer has a websocket for presence
