### ISSUE TITLE
Status listed as "Playing a game"

### ISSUE THREAD

**Issue by 3my** [PvtTyphoon/lfm-rich-presence#8]
Love this project, works great so far. Is there a way to get the status message changed from "Playing a game" to something like "Listening to"? Not a huge deal but would be a good addition

**Comment by PvtTyphoon** [comment]
Discord doesn't allow third party clients to use the "Listening to" activity type, look [here](https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum), the Activity Type Enum is discarded unless it's a special case, i.e., Spotify and other partnered platforms
