### ISSUE TITLE
Require ESM error on run. (Linux Mint)

### ISSUE THREAD

**Issue by dm2912** [PvtTyphoon/lfm-rich-presence#9]
System: Linux Mint 20.x

Crashes with a Require ESM error. Did a bit of googling on Require ESM generally but all double dutch to me :dagger: 

Terminal output:

```node main.js
/home/dim/lastfm2discord/main.js:6
const prettyMilliseconds = require("pretty-ms");
                           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dim/node_modules/pretty-ms/index.js from /home/dim/lastfm2discord/main.js not supported.
Instead change the require of index.js in /home/dim/lastfm2discord/main.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/dim/lastfm2discord/main.js:6:28) {
  code: 'ERR_REQUIRE_ESM'
}```

**Comment by PvtTyphoon** [comment]
Running from the script requires you to install the required packages from NPM first

**Comment by dm2912** [comment]
> Running from the script requires you to install the required packages from NPM first

yeh, they are. everything is installed

the error is that ~/node_modules/pretty-ms/ which is default install location in buntu is not allowed by the script.  Error says to change it to a dynamic import instead?

everything already installed

```
npm i discord-rpc request-promise pretty-ms

up to date, audited 65 packages in 4s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

error persists

```/home/dim/lastfm2discord/main.js:6
const prettyMilliseconds = require("pretty-ms");
                           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dim/node_modules/pretty-ms/index.js from /home/dim/lastfm2discord/main.js not supported.
Instead change the require of index.js in /home/dim/lastfm2discord/main.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/dim/lastfm2discord/main.js:6:28) {
  code: 'ERR_REQUIRE_ESM'
```

"change require of index.js to a dynamic import"

**Comment by whatever1337** [comment]
downgrade your pretty-ms

`npm i pretty-ms@7.0.1`

**Comment by whatever1337** [comment]
> System: Linux Mint 20.x
> 
> Crashes with a Require ESM error. Did a bit of googling on Require ESM generally but all double dutch to me 🗡️
> 
> Terminal output:
> 
> ```js
> /home/dim/lastfm2discord/main.js:6
> const prettyMilliseconds = require("pretty-ms");
>                            ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dim/node_modules/pretty-ms/index.js from /home/dim/lastfm2discord/main.js not supported.
> Instead change the require of index.js in /home/dim/lastfm2discord/main.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (/home/dim/lastfm2discord/main.js:6:28) {
>   code: 'ERR_REQUIRE_ESM'
> }```
> ```

downgrade your pretty-ms

`npm i pretty-ms@7.0.1`

**Comment by dm2912** [comment]
ive moved to kubuntu 22, so will test later in that and see if issue persists or will use whatevers solution :D
